#设置服务器的端口号
server:
  port: 8080
#数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_1805?userSSL=false&serverTimezone=GMT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
#  mapper-locations:

#配置MyBatis